// client/src/views/Game.tsx
import { useSelector } from "react-redux"
import DiceRoll from "../components/DiceRoll"
import Page from "../components/Page"
import ScoreCard from "../components/ScoreCard"
import type { PlayerState } from "../slices/player_slice"
import type { State } from "../stores/store"
import { useNavigate, useParams } from "react-router"
import * as Ongoing from "../slices/ongoing_games_slice"
import type { IndexedYahtzee } from "../model/game"
import { is_finished, scores } from "domain/src/model/yahtzee.game"
import * as _ from 'lodash/fp'
import { useEffect } from "react"
import './Game.css'

export default () => {
  const params = useParams()
  const {player} = useSelector<State, PlayerState>(state => state.player)
  const id = params.id!
  const game = useSelector<State, IndexedYahtzee | undefined>(state => Ongoing.game(id, state.ongoing_games))
  const navigate = useNavigate()

  useEffect(() => {
    if (player === undefined) {
      navigate(`/login?game=${id}`)
    } else if (game === undefined) {
      navigate('/')
    }
  }, [player, game])

  if (player === undefined || game === undefined) return <></>

  const enabled = player === game.players[game.playerInTurn]
  const finished = is_finished(game)
  const standings = _.sortBy(_.last, scores(game).map((s, i) => [game.players[i], s]))

  return player && <Page>
    <div className="game">
      <div className="meta">
        <h1>Game #{id} </h1>
      </div>
      {game && <ScoreCard className="card" game={game} player={player} enabled={enabled}/>}
      {!finished && <DiceRoll className="roll" game={game!} player={player} enabled={enabled}/>}
      {finished && <div className="scoreboard">
        <table>
          <thead><tr><td key='player'>Player</td><td key='score'>Score</td></tr></thead>
          <tbody>
            {standings.map(row => <tr className={row[0] == player? 'current' : undefined} key={row[0]}><td key='player'>{row[0]}</td><td key='score'>{row[1]}</td></tr>)}
          </tbody>
        </table>
      </div>}
    </div>
  </Page>
}

// client/src/views/Game.vue
<script setup lang="ts">
  import {useOngoingGamesStore} from '@/stores/ongoing_games_store';
  import DiceRoll from '../components/DiceRoll.vue'
  import ScoreCard from '../components/ScoreCard.vue'
  import { useRoute, useRouter } from 'vue-router';
  import { computed, ref, watch } from 'vue';
  import {usePlayerStore} from '@/stores/player_store';
  import Page from '@/components/Page.vue';
  import { is_finished, scores } from 'domain/src/model/yahtzee.game';

  const ongoingGameStore = useOngoingGamesStore()
  const playerStore = usePlayerStore()
  const route = useRoute()
  const router = useRouter()

  let id = ref(route.params.id.toString())
  watch(() => route.params.id, (newId) => id.value = newId.toString())
  const game = computed(() => ongoingGameStore.game(id.value))
  const enabled = computed(() => game.value !== undefined && playerStore.player === game.value.players[game.value.playerInTurn])
  const finished = computed(() => game.value === undefined || is_finished(game.value))
  const standings = computed(() => {
    if (game.value === undefined) return []
    const g = game.value
    const standings: [string, number][] = scores(g).map((s, i) => [g.players[i], s])
    standings.sort(([_, score1], [__, score2]) => score2 - score1)
    return standings
  })

  if (playerStore.player === undefined)
    router.push(`/login?game=${id.value}`)
  else if (game.value === undefined)
    router.replace('/')
  
</script>

<template>
  <Page v-if="game && playerStore.player">
    <div class="game">
      <div class="meta">
        <h1>Game #{{id}} </h1>
      </div>
      <ScoreCard class="card" :game="game" :player="playerStore.player" :enabled="enabled"/>
      <DiceRoll v-if="!finished" class ="roll" :game="game" :player="playerStore.player" :enabled="enabled"/>
      <div v-if="finished" class="scoreboard">
        <table>
          <thead><tr><td>Player</td><td>Score</td></tr></thead>
          <tbody>
            <tr v-for="row in standings" :class="row[0] == playerStore.player? 'current' : undefined"><td>{{row[0]}}</td><td>{{row[1]}}</td></tr>
          </tbody>
        </table>
      </div>
    </div>
  </Page>
</template>

<style>
  .roll {
    margin: .3rem 1rem;
  }
  .scoreboard {
    display: inline-block;
    margin: .3rem 1rem;
  }
  .scoreboard thead {
    font-weight: bold;
    font-size: large;
  }
  .scoreboard > table {
    border: 1px solid black;
    border-collapse: collapse;
  }
  .scoreboard td {
    border: 1px solid black;
    border-collapse: collapse;
    padding: .2rem
  }
  .current {
    font-weight: bold;
    background-color: firebrick;
    color: lavenderblush;
  }
  .game {
    contain: content;
  }
  .card {
    float: left;
  }
</style>
