// client/src/components/Page.tsx
import * as React from 'react'
import { useSelector } from 'react-redux'
import { Link } from 'react-router'
import type { State } from '../stores/store'
import type { PlayerState } from '../slices/player_slice'
import type { OngoingGamesState } from '../slices/ongoing_games_slice'
import type { PendingGamesState } from '../slices/pending_games_slice'
import * as _ from 'lodash/fp'
import { is_finished } from 'domain/src/model/yahtzee.game'

export default ({children}: {children: React.ReactNode}) => {
  const {player} = useSelector<State, PlayerState>(state => state.player)
  const ongoing_games = useSelector<State, OngoingGamesState>(state => state.ongoing_games)
  const pending_games = useSelector<State, PendingGamesState>(state => state.pending_games)

  const is_participant = (g: {players: readonly string[]}) => g.players.some(_.isEqual(player))

  const my_ongoing_games = ongoing_games.filter(is_participant).filter(_.negate(is_finished))
  const my_pending_games = pending_games.filter(is_participant)
  const other_pending_games = pending_games.filter(_.negate(is_participant))

  return <>
    <h2 className="subheader">Welcome player {player}</h2>
    <nav>
      <Link className='link' to="/">Lobby</Link>
      
      <h2>My Games</h2>
      <h3>Ongoing</h3>
      {my_ongoing_games.map(game => <Link className='link' to={`/game/${game.id}`} key={game.id}>Game #{game.id}</Link>)}
      
      <h3>Waiting for players</h3>
      {my_pending_games.map(game => <Link className='link' to={`/pending/${game.id}`} key={game.id}>Game #{game.id}</Link>)}
      
      <h2>Available Games</h2>
      {other_pending_games.map(game => <Link className='link' to={`/pending/${game.id}`} key={game.id}>Game #{game.id}</Link>)}
    </nav>
    
    {children}
  </>
}

// client/src/components/Page.vue
<script setup lang="ts">
  import { RouterLink } from 'vue-router'
  import { computed } from 'vue'
  import { useOngoingGamesStore } from '../stores/ongoing_games_store';
  import {usePlayerStore} from '../stores/player_store';
  import {usePendingGamesStore} from '../stores/pending_games_store';
import { is_finished } from 'domain/src/model/yahtzee.game';
  
  const ongoingGamesStore = useOngoingGamesStore()
  const pendingGamesStore = usePendingGamesStore()
  const playerStore = usePlayerStore()
  
  const isParticipant = (g: {players: readonly string[]}) => g.players.indexOf(playerStore.player ?? '') > -1
  
  const my_ongoing_games = computed(() => ongoingGamesStore.games.filter(g => isParticipant(g) && !is_finished(g)))
  const my_pending_games = computed(() => pendingGamesStore.games.filter(isParticipant))
  const other_pending_games = computed(() => pendingGamesStore.games.filter(g => !isParticipant(g)))
</script>

<template>
  <h2 class="subheader">Welcome player {{playerStore.player}}</h2>
  <nav>
    <RouterLink class='link' to="/">Lobby</RouterLink>
    
    <h2>My Games</h2>
    <h3>Ongoing</h3>
    <RouterLink class='link' v-for="game in my_ongoing_games" :to="`/game/${game.id}`">Game #{{game.id}}</RouterLink>
    
    <h3>Waiting for players</h3>
    <RouterLink class='link' v-for="game in my_pending_games" :to="`/pending/${game.id}`">Game #{{game.id}}</RouterLink>
    
    <h2>Available Games</h2>
    <RouterLink class='link' v-for="game in other_pending_games" :to="`/pending/${game.id}`">Game #{{game.id}}</RouterLink>
  </nav>
  
  <slot class='main'></slot>
</template>
